version: '3'
services:
  fpm:
    container_name: converter_fpm
    image: bitnami/php-fpm
    restart: always
    cap_add:
      - ALL
    volumes:
      - ./:/app
    ports:
      - '8000:80'
  nginx-chat:
      container_name: converter_nginx
      image: nginx
      restart: always
      depends_on:
        - fpm
      links:
        - fpm:fpm.local
      ports:
      - "8232:80"
      volumes:
          - ./:/app
          - ./docker/nginx/:/etc/nginx/conf.d